name: starterkit_app
description: A new Flutter project.
publish_to: "none"
version: 0.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  auto_mappr_annotation: ^2.3.0
  auto_route: ^10.1.0+1
  collection: ^1.19.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  drift: ^2.28.0
  drift_flutter: ^0.2.5
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path: ^1.9.1
  path_provider: ^2.1.5
  retrofit: ^4.6.0
  uuid: ^4.5.1

dev_dependencies:
  auto_mappr: ^2.9.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  drift_dev: ^2.28.0
  flutter_gen_runner: ^5.11.0
  flutter_test:
    sdk: flutter
  full_coverage: ^1.0.0
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.7.0
  intl_utils: ^2.8.11
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  retrofit_generator: ^9.7.0

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/common/resources
  line_length: 120
  fonts:
    enabled: false

flutter_intl:
  enabled: true
  class_name: Il8n
  arb_dir: lib/common/localization
  output_dir: lib/common/localization/generated
